version: "3"

services:
  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"

  grpc-client:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - grpc-server
